### ISSUE TITLE
As a developer, I want to migrate to freeipa client library 1.0.0 

### ISSUE THREAD

**Issue by abompard** [fedora-infra/noggin#94] opened 2020-01-30 09:13 UTC
We are currently using the [python-freeipa](https://python-freeipa.readthedocs.io) library ([source code](https://github.com/opennode/python-freeipa)), which is not the official client library and has recently been updating to version 1.0.0, breaking compatibility with what we were using. They do provide a legacy module with a compatible class, so we can keep using it for now, but before we adapt to the non-legacy code we should decide whether we want to keep using that library or move to the official [freeipa client library](https://github.com/freeipa/freeipa/tree/master/ipaclient), which is also used to power the `ipa` command line, and as a result can do all operations that the command line provides. The current client is lacking some operations and we've had to extend it.
However, @relrod said that the official library is harder to use, and we may need help from the FreeIPA team if we decide to use it. I think we should investigate those options.

**Comment by abompard** [comment] 2020-01-30 12:42
I looked at python-freeipa v1.0.0, and they are autogenerating their classes from the official FreeIPA API spec, which means that they will be complete and more easily up-to-date with any upstream changes. I think that's a positive element for choosing to stay with python-freeipa and adopt 1.0.0, but I'd be happy to head other opinions.

**Comment by relrod** [comment] 2020-01-30 14:13
I have a changeset started on my laptop to port to 1.0.0. The issue is they don't pass kwargs in things like `user_mod` so we can't update things like our custom fas attributes unless I'm missing something.

I believe we'll need to ask them to either accept and pass along kwargs or accept a dict with extra args.

**Comment by abompard** [comment] 2020-01-30 14:16
Indeed, that seems necessary.

**Comment by sfinn85** [comment] 2020-02-04 15:25
Free IPA library needs to be updated, we need to reach out to try get this updated

**Comment by relrod** [comment] 2020-02-05 08:41
This isn't blocking anything. This is a nicetohave. The legacy client in python-freeipa works just fine for now until we sort out how to get 1.0.0 to work for us (something I've started on but need to reach out to upstream on).

This is something we can address later.

**Comment by sfinn85** [comment] 2020-02-06 10:45
Sprint planning 3 update: 
Upstream community engagement needed - Tech Debt
Possibly a James task AC & DOD to be added early next week

**Comment by relrod** [comment] 2020-02-06 17:31
I'm really not sure this needs to be addressed in sprint 3, this is blocking nothing at all right now.

**Comment by james02135** [comment] 2020-02-07 09:36
During the sprint planning call yesterday, this was identified as an issue appropriate for me to work on as an intern.

**Comment by Conan-Kudo** [comment] 2020-04-14 01:25
`python-freeipa` v1.0.2 has been packaged for Fedora and EPEL 8:

* F32: https://bodhi.fedoraproject.org/updates/FEDORA-2020-81f9f75f04
* F31: https://bodhi.fedoraproject.org/updates/FEDORA-2020-217b6928cc
* F30: https://bodhi.fedoraproject.org/updates/FEDORA-2020-06730065a6
* EPEL8: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-a729ac8728

It has also been packaged for openSUSE and is awaiting merge into Tumbleweed and Leap 15.2:

* Tumbleweed: https://build.opensuse.org/request/show/793700
* Leap 15.2: https://build.opensuse.org/request/show/793701

Please aim for at least this version when bumping the `python-freeipa` dependency.

**Closed as completed** 2020-08-03 10:58 UTC
Labels: L
