### ISSUE TITLE
As a user, i want to see detailed information about a group

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/noggin#20] opened 2019-12-23 15:50 UTC

**Comment by ryanlerch** [comment] 2020-02-04 03:49
@relrod @sfinn85 While not really a duplicate of #36, The group listing page as currently implemented appears to fulfill this user story already.

**Comment by sfinn85** [comment] 2020-02-04 12:58
Thanks for flagging, were we looking at more detail here than we currently have? Does the group wireframe give sufficient detailed information? see user story here, a screenshot has been added
https://github.com/fedora-infra/securitas/issues/3 thoughts @abompard @relrod

**Comment by sfinn85** [comment] 2020-02-11 14:18
Request for membership of group. Aoife to follow up with what is meant by detailed information

**Comment by amoloney1** [comment] 2020-02-12 10:03
Requirements for this ticket:

- As a user, I want to be able to see who is in a group, to see if my friends are in it
- As a user, I want to see what a specific group is responsible for, so I know what they work on/are interested in
- As a user, I want to be able to see who is the group sponsor, so I can report an issue that their group is responsible for
- As a user, I want to be able to see who is the group admin so I can reach out to them to request membership

**Comment by abompard** [comment] 2020-02-12 16:02
I think "group sponsor" and "group admin" are the same thing.
In that case we already show those pieces of information.

**Closed as completed** 2020-02-20 10:28 UTC
Labels: maybe done?
