### ISSUE TITLE
fasClient replacement plan

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#195] opened 2020-04-02 20:59 UTC
Not sure this should be ticket, but not sure where else to file it. 

With the old fas setup, we had a client called 'fasClient' that runs on servers. It fetches user ssh keys and information and makes nssdb passwd/shadow files, a homedirectory and ssh authorized_keys. 
It added only those users that were in allowed groups for that host. 

I know there were a number of replacements suggested for this setup, but I don't know if we decided on one or still need to. 

Basically the requirements would be: 
* allow ssh access to groups to specific machines
* ideally allow that access to keep working if the machine wasn't able to query the noggin server
* allow ssh access to the 'accepted cla + 1' group

I think freeipa ties into sssd for it's ssh access. Is that an option for us? 

Or we also talked about a small service/scripting that would query noggin and generate ssh _certs_ for access. There's some apps out there that already do this, although they might be too complex for our needs. (ex https://github.com/Netflix/bless )

So, we should try and figure out the story here. Perhaps we should discuss more on list or have a meeting or two to discuss requirements.

**Comment by abompard** [comment] 2020-04-03 08:36
Duplicate of #196

**Closed as completed by abompard** 2020-04-03 08:36 UTC
